PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS VaiTro (
  MaVaiTro INTEGER PRIMARY KEY AUTOINCREMENT,
  TenVaiTro TEXT NOT NULL UNIQUE,
  TenVietTat TEXT
);

CREATE TABLE IF NOT EXISTS NguoiDung (
  MaNguoiDung INTEGER PRIMARY KEY AUTOINCREMENT,
  MaVaiTro INTEGER NOT NULL REFERENCES VaiTro(MaVaiTro),
  TenNguoiDung TEXT NOT NULL,
  Email TEXT NOT NULL UNIQUE,
  MatKhau TEXT NOT NULL,
  SoDienThoai TEXT,
  TrangThai TEXT DEFAULT 'active',
  NgayTao TEXT DEFAULT CURRENT_TIMESTAMP,
  NgayCapNhat TEXT,
  FOREIGN KEY (MaVaiTro) REFERENCES VaiTro(MaVaiTro) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS KhachSan (
  MaKhachSan INTEGER PRIMARY KEY AUTOINCREMENT,
  TenKhachSan TEXT NOT NULL,
  DiaChi TEXT,
  MoTa TEXT,
  NguoiDungId INTEGER REFERENCES NguoiDung(MaNguoiDung),
  DienThoai TEXT,
  XepHang INTEGER CHECK(XepHang BETWEEN 1 AND 5),
  NgayTao TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Phong (
  MaPhong INTEGER PRIMARY KEY AUTOINCREMENT,
  MaKhachSan INTEGER NOT NULL REFERENCES KhachSan(MaKhachSan) ON DELETE CASCADE,
  SoPhong TEXT NOT NULL,
  LoaiPhong TEXT,
  SoLuongNguoi INTEGER,
  Gia REAL NOT NULL,
  TrangThai TEXT DEFAULT 'available'
);

CREATE TABLE IF NOT EXISTS DichVu (
  MaDichVu INTEGER PRIMARY KEY AUTOINCREMENT,
  MaNguoiDung INTEGER REFERENCES NguoiDung(MaNguoiDung),
  TenDichVu TEXT NOT NULL,
  MoTa TEXT,
  HinhAnh TEXT,
  HinhAnhBoSuuTap TEXT,
  Gia REAL,
  GiaNguoiLon REAL,
  GiaTreEm REAL,
  ThoiLuong TEXT,
  DiaDiem TEXT,
  LoaiDichVu TEXT DEFAULT 'tour',
  NgayTao TEXT DEFAULT CURRENT_TIMESTAMP,
  NgayCapNhat TEXT,
  FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung)
);

CREATE TABLE IF NOT EXISTS DatPhong (
  MaDatPhong INTEGER PRIMARY KEY AUTOINCREMENT,
  MaNguoiDung INTEGER NOT NULL REFERENCES NguoiDung(MaNguoiDung),
  MaKhachSan INTEGER NOT NULL REFERENCES KhachSan(MaKhachSan),
  MaPhong INTEGER NOT NULL REFERENCES Phong(MaPhong),
  NgayNhan TEXT NOT NULL,
  NgayTra TEXT NOT NULL,
  SoNguoi INTEGER DEFAULT 1,
  TrangThai TEXT DEFAULT 'pending',
  NgayTao TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DatDichVu (
  MaDatDichVu INTEGER PRIMARY KEY AUTOINCREMENT,
  MaNguoiDung INTEGER NOT NULL REFERENCES NguoiDung(MaNguoiDung),
  MaDichVu INTEGER NOT NULL REFERENCES DichVu(MaDichVu),
  SoLuong INTEGER DEFAULT 1,
  GhiChu TEXT,
  TrangThai TEXT DEFAULT 'pending',
  NgayDat TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS GiaoDich (
  MaGiaoDich INTEGER PRIMARY KEY AUTOINCREMENT,
  MaNguoiDung INTEGER REFERENCES NguoiDung(MaNguoiDung),
  MaDatPhong INTEGER REFERENCES DatPhong(MaDatPhong),
  MaDatDichVu INTEGER REFERENCES DatDichVu(MaDatDichVu),
  SoTien REAL NOT NULL,
  PhuongThucTT TEXT,
  TrangThai TEXT DEFAULT 'pending',
  NgayGiaoDich TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DanhGia (
  MaDanhGia INTEGER PRIMARY KEY AUTOINCREMENT,
  MaNguoiDung INTEGER NOT NULL REFERENCES NguoiDung(MaNguoiDung),
  MaKhachSan INTEGER REFERENCES KhachSan(MaKhachSan),
  MaDichVu INTEGER REFERENCES DichVu(MaDichVu),
  Diem INTEGER CHECK(Diem BETWEEN 1 AND 5),
  NoiDung TEXT,
  NgayDanhGia TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ThongBao (
  MaThongBao INTEGER PRIMARY KEY AUTOINCREMENT,
  MaNguoiDung INTEGER NOT NULL REFERENCES NguoiDung(MaNguoiDung),
  TieuDe TEXT NOT NULL,
  NoiDung TEXT,
  DaDoc INTEGER DEFAULT 0,
  NgayTao TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BaiViet (
  MaBaiViet INTEGER PRIMARY KEY AUTOINCREMENT,
  TieuDe TEXT NOT NULL,
  NoiDung TEXT,
  MaNguoiDung INTEGER REFERENCES NguoiDung(MaNguoiDung),
  NgayTao TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS LichSuChatbot (
  MaChat INTEGER PRIMARY KEY AUTOINCREMENT,
  MaNguoiDung INTEGER REFERENCES NguoiDung(MaNguoiDung),
  CauHoi TEXT,
  TraLoi TEXT,
  ThoiGian TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS NhatKyHeThong (
  MaNhatKy INTEGER PRIMARY KEY AUTOINCREMENT,
  MaNguoiDung INTEGER REFERENCES NguoiDung(MaNguoiDung),
  NoiDung TEXT,
  MucDo TEXT,
  ThoiGian TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DatTour (
  MaDatTour INTEGER PRIMARY KEY AUTOINCREMENT,
  MaDichVu INTEGER NOT NULL REFERENCES DichVu(MaDichVu) ON DELETE CASCADE,
  TenKhach TEXT NOT NULL,
  Email TEXT NOT NULL,
  DienThoai TEXT NOT NULL,
  SoNguoi INTEGER DEFAULT 1,
  SoNguoiLon INTEGER DEFAULT 1,
  SoTreEm INTEGER DEFAULT 0,
  NgayKhoiHanh TEXT,
  GhiChu TEXT,
  TrangThai TEXT DEFAULT 'pending',
  NgayTao TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Seed default roles
INSERT INTO VaiTro (TenVaiTro, TenVietTat)
SELECT 'Admin', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM VaiTro WHERE TenVaiTro = 'Admin');

INSERT INTO VaiTro (TenVaiTro, TenVietTat)
SELECT 'User', 'USER'
WHERE NOT EXISTS (SELECT 1 FROM VaiTro WHERE TenVaiTro = 'User');

